### ISSUE TITLE
Support dynamic labels from ROS topics

### ISSUE THREAD

**Issue by AnthonyCvn** [reductstore/reductstore_agent#14]
Allow each pipeline to define **labels** sourced from ROS 2 topics.
The agent should extract fields at write time, using a configurable **mode** per topic:

* `last` → use the most recent message (default)
* `first` → use the first message in the current file
* `max` → use the maximum value across all messages in the file

Example:

```yaml
labels:
  - topic: "/mission_info"
    mode: last        # options: last|first|max (default: last)
    fields:
      mission_id: mission_id   # label_name: msg_field
      operator: operator
  - topic: "/telemetry"
    mode: max
    fields:
      max_speed: speed
```
